#!/bin/bash
# Test viewer with debug logging

echo "=== Starting relay with debug logging ==="
echo ""
echo "1. Start the relay: ./cams-relay"
echo "2. Open browser to http://localhost:8080"
echo "3. Open browser console (F12)"
echo "4. Look for these debug messages:"
echo ""
echo "   [Camera XXX] Pulling tracks: {...}"
echo "   [Camera XXX] Received tracks response: {...}"
echo "   [Camera XXX] Extracted SDP offer, length: XXX"
echo "   [Camera XXX] Setting remote description, SDP length: XXX"
echo "   [Camera XXX] Creating answer"
echo "   [Camera XXX] Set local description, answer SDP length: XXX"
echo "   [Camera XXX] Sending renegotiate request, answer SDP length: XXX"
echo "   [Camera XXX] Renegotiate response: {...}"
echo "   [Camera XXX] Renegotiation complete"
echo "   [Camera XXX] WebRTC negotiation complete"
echo "   [Camera XXX] ICE state: checking/connected"
echo "   [Camera XXX] Connection state: connecting/connected"
echo "   [Camera XXX] Received track: video"
echo ""
echo "=== What to look for ==="
echo ""
echo "1. Does 'Received tracks response' show valid sessionDescription?"
echo "2. Does 'Extracted SDP offer' succeed?"
echo "3. Does answer creation succeed?"
echo "4. Does renegotiate response show {}?"
echo "5. Do ICE states progress: new -> checking -> connected?"
echo "6. Do we receive track events?"
echo ""
echo "=== Common Issues ==="
echo ""
echo "Issue: No SDP offer"
echo "  - Check 'Received tracks response' structure"
echo "  - Backend should return: {sessionDescription: {sdp: '...', type: 'offer'}, ...}"
echo ""
echo "Issue: ICE state stays 'checking'"
echo "  - ICE candidates not reaching Cloudflare"
echo "  - Check firewall/NAT"
echo ""
echo "Issue: Connection state 'failed'"
echo "  - ICE negotiation failed"
echo "  - Check STUN server reachability"
echo ""
echo "Issue: No track event"
echo "  - Connection successful but no media"
echo "  - Check backend camera streams are active"
echo ""
